### ISSUE TITLE
No "Bill" after refueling the Car

### ISSUE THREAD

**Issue by Zaickz** [AsYetUntitled/Framework#293] opened 2017-03-11 10:41 UTC
File: fn_fuelRefuelCar.sqf
### Expected behaviour
That you have to pay for your fuel that you got from the Gasstation. 

CASH = CASH - (FUEL*FUELPRICE)

### Actual behaviour
You dont have to pay for the fuel. If you have 4000 Cash and you have to pay 60 Cashfor your fuel you stay with your 4000 Cash. But your Car is full of fuel

## The check if you have enough Money does work.

I already changed CASH to BANK same problem.

**Comment by BoGuu** [comment] 2017-03-11 11:10
Can you please follow the proper issue format. And for your actual behaviour you've said it does work?

**Comment by fresqo** [comment] 2017-03-11 11:48
in the script its BANK, why are you referring to CASH at all?

**Comment by S0pex** [comment] 2017-03-11 22:37
I guess he means that you have to pay the bill after your car is refueled, so you refuel your car and dont pay the bill, the car still has the fuel

**Comment by Jawshy** [comment] 2017-09-28 08:00
Duplicate of https://github.com/AsYetUntitled/Framework/issues/210.

**Closed** 2018-08-19 16:45 UTC
Labels: duplicate, minor-bug
