### ISSUE TITLE
Players spawn naked

### ISSUE THREAD

**Issue by setoy** [AsYetUntitled/Framework#103] opened 2016-09-22 17:56 UTC
### Expected behaviour
You shouldn't spawn naked.

### Actual behaviour
Well, players spawn naked...

### Steps to reproduce the behaviour 
1. Spawn, abort mission and re-spawn

### RPT and/or extDB2 logs (if applicable)
http://hastebin.com/uhipejizib.vbs

----

Launcher version: 1.5.138489

Game version: 1.64.138497

Branch: main / beta branch not specified

Started with 1.64

**Comment by Jawshy** [comment] 2016-09-22 17:58
Duplicate of https://github.com/AsYetUntitled/Framework/issues/81.

**Comment by tkcjesse** [comment] 2016-09-22 17:58
Much description. Much wow.

**Closed by Jawshy** 2016-09-22 17:58 UTC

**Comment by setoy** [comment] 2016-09-22 17:59
Nothing more is needed to reproduce this ;)

**Comment by BoGuu** [comment] 2016-09-22 18:03
https://github.com/AsYetUntitled/Framework/issues/104
