### ISSUE TITLE
Spike Strip issue

### ISSUE THREAD

**Issue by IceEagle132** [AsYetUntitled/Framework#416] opened 2018-01-07 10:41 UTC
When you place a spike strip down and someone runs them over you can no longer place another one down. It says you have one down even tho a car hit it and it was deleted. Only way to be able to use another is to leave to server lobby and rejoin.

**Comment by Jawshy** [comment] 2018-01-07 10:45
Duplicate of https://github.com/AsYetUntitled/Framework/issues/212. Use the [search function](https://github.com/AsYetUntitled/Framework/blob/master/.github/CONTRIBUTING.md#before-creating-a-new-issue-make-sure-to) and [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md) when reporting bugs, @IceEagle132.

**Closed by Jawshy** 2018-01-07 10:45 UTC
Labels: duplicate, minor-bug
