### ISSUE TITLE
Binoculars don't get removed when you sell them

### ISSUE THREAD

**Issue by JManL46** [AsYetUntitled/Framework#495] opened 2018-10-18 16:57 UTC
### Expected behaviour
They get removed from the slot.

### Actual behaviour
When you sell binoculars, they don't get removed if they are in the slot in the top right of the inventory menu. Although, they do get removed if they are in your clothes, vest or backpack.

### Steps to reproduce the behaviour
1. Sell a pair of binoculars which are in the top right slot of the inventory menu

----

Mission version: 5.0

Launcher version: 1.5.144923

Game version: 1.84.144923

Branch: main

**Comment by baua1310** [comment] 2018-10-18 17:55
Duplicate of: https://github.com/AsYetUntitled/Framework/issues/264

**Comment by Jason2605** [comment] 2018-12-20 19:58
Duplicate issue, thanks @baua1310.

**Closed by Jason2605** 2018-12-20 19:58 UTC
