### ISSUE TITLE
Unaccessible

### ISSUE THREAD

**Issue by RickDBCN** [AsYetUntitled/Framework#409] opened 2018-01-02 01:49 UTC
Hi,

When I try to start my server, it gives me the following error:
```
"extDB3: Connected to Database"
"----------------------------------------------------------------------------------------------------"
"---------------------------------- Starting Altis Life Server Init ---------------------------------"
"------------------------------------------ Version 5.0.0 -------------------------------------------"
"----------------------------------------------------------------------------------------------------"
Error in expression <fe",count playableUnits,true];
[] spawn TON_fnc_federalUpdate;


addMissionEvent>
  Error position: <TON_fnc_federalUpdate;


addMissionEvent>
  Error Undefined variable in expression: ton_fnc_federalupdate
File life_server\init.sqf, line 143
"----------------------------------------------------------------------------------------------------"
"               End of Altis Life Server Init :: Total Execution Time 0.841003 seconds "
"----------------------------------------------------------------------------------------------------"
Error in expression <r_1,Dealer_2,Dealer_3];
};
};

[] spawn TON_fnc_initHouses;
cleanup = [] spawn T>
  Error position: <TON_fnc_initHouses;
cleanup = [] spawn T>
  Error Undefined variable in expression: ton_fnc_inithouses
File life_server\init.sqf, line 174
Unaccessible
No speaker given for Rhys Abbey
Speaker Male01_F not found in CfgVoiceTypes
```

extdb3 log

```
extDB3: https://bitbucket.org/torndeco/extdb3/wiki/Home
extDB3: Version: 1.030
extDB3: Windows Version
Message: All development for extDB3 is done on a Linux Dedicated Server
Message: If you would like to Donate to extDB3 Development
Message: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2SUEFTGABTAM2
Message: Also leave a message if there is any particular feature you would like to see added.
Message: Thanks for all the people that have donated.
Message: Torndeco: 18/05/15


extDB3: Found extdb3-conf.ini
extDB3: Detected 8 Cores, Setting up 6 Worker Threads
extDB3: ...
extDB3: ...
extDB3: ...
extDB3: ...
extDB3: ...
extDB3: ...


[01:51:07:706298 +01:00] [Thread 9112] extDB3: SQL: Initialized: Add Quotes around TEXT Datatypes mode: 2
[01:51:07:706709 +01:00] [Thread 9112] extDB3: SQL: Initialized: NULL = ""
[01:51:07:706744 +01:00] [Thread 9112] extDB3: Locked
```

When I try to log in Unaccessible shows up. What's going on?

**Comment by Jawshy** [comment] 2018-01-02 01:55
@RickDBCN, this looks like a user error caused by editing the mission files and not an issue with the framework itself. As issue tickets are only for issues with the framework and not for support I will close this issue. 

Feel free to ask for help in the [Discord server](https://discord.gg/EaB7Jgw) in #troubleshooting.

**Closed by Jawshy** 2018-01-02 01:55 UTC
